---
- hosts: localhost
  name: get disk-space usage
  roles:
    - pan
  gather_facts: False
  tasks:
    - name: bare include (free-form)
      include_vars: vars.yml
      dir: roles/pan/vars/
    - name: Show disk-space usage
      show_disk_space:
        pan_api_key: "{{ api['key'] }}"
        pan_cmd: "{{ cmd['show_disk_space'] }}"
        pan_api_url: "{{ api['url'] }}"
        secretkey: "{{ secret }}"
