---
- hosts: 192.168.200.112
  roles:
    - pan
  gather_facts: !all
  tasks:
    - name: Show disk-space usage
      show_disk_space:
        pan_api_key: "{{ api['key'] }}"
        pan_cmd: "{{ cmd['show_disk_space'] }}"
        pan_api_url: "{{ api['url'] }}"
      register: result
