---
- hosts: localhost

  tasks:
    - name: Show disk-space usage
      include_vars: vaulted_vars.yml
      show_disk_space:
        pan_api_key: "{{api_key}}"
        pan_cmd: "{{show_disk_space}}"
        pan_api_url: "{{pan_api_url}}"
      register: result
