---
- hosts: Test_Group
  name: get disk-space usage
  roles:
    - pan
  gather_facts: True
  tasks:
    - name: Show disk-space usage
      show_disk_space:
        pan_api_key: "{{ pan.api.key }}"
        pan_cmd: "{{ pan.cmd.show_disk_space }}"
        pan_api_url: "{{ pan.api.url }}"
        secretkey: "{{ secret }}"
...