---
- hosts: Minepi_Group
  name: Check if director exists
  gather_facts: False
  tasks:
    - name: Stat minecraft directory
      stat:
        path: "{{ mc_path }}"
      register: p
    - name: Create directory
      file:
        path: "{{ mc_path }}"
        state: directory
      when: p.stat.isdir is defined and p.stat.isdir
