---
- hosts: Inspiron
  name: Update Minecraft Server
  gather_facts: False
  roles:
    - minecraft
  tasks:
#    - name: Stop Minecraft Server
#      shell: /usr/bin/screen -X -S minecraft quit
#      ignore_errors: yes
    - name: Stat minecraft directory
      stat:
        path: "{{ mc_path }}"
      register: p
    - name: Determine if new install or update
      set_fact:
        new_install: true
      notify: "new install"
      when: p.stat.exists == False
    - meta: flush_handlers
    - name: Download latest Jenkins build
      get_url:
        url: https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        dest: "{{ mc_path }}/BuildTools.jar"
        force: yes
    - name: Build Jar file
      shell: "/usr/bin/java -jar {{ mc_path }}/BuildTools.jar"
      args:
        chdir: "{{ mc_path }}"
    - name: Get spigot file name
      shell: /bin/ls -1c spigot*.jar | head -1
      args:
        chdir: "{{ mc_path }}"
      register: ls_output
    - name: Copy updated minecraft.sh script
      template:
        src: roles/minecraft/templates/minecraft.sh.j2
        dest: "{{ mc_path }}/minecraft.sh"
        mode: 0755
    - name: Edit rc.local
      lineinfile:
        path: "/etc/rc.local"
        regexp: '^su -l pi'
        line: 'su -l pi -c {{ mc_path }}/minecraft.sh'
      become: yes
#    - name: Start Minecraft Server
#      shell: "{{ mc_path }}/minecraft.sh"
  handlers:
    - name: Create directory
      file:
        path: "{{ mc_path }}"
        state: directory
      listen: "new install"
    - name: Copy plugins
      copy:
        src: roles/minecraft/files/plugins
        dest: "{{ mc_path }}/"
      listen: "new install"
    - name: Copy admin
      copy:
        src: roles/minecraft/files/admin.txt
        dest: "{{ mc_path }}/admin.txt"
      listen: "new install"
    - name: Copy eula
      copy:
        src: roles/minecraft/files/eula.txt
        dest: "{{ mc_path }}/eula.txt"
      listen: "new install"