---
- hosts: Test_Group
  name: Update Minecraft Server
  gather_facts: False
  tasks:
    - name: Quit the screen session
      shell: screen -X -S minecraft quit
    - name: Download latest Jenkins build
      get_url:
        url: https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        dest: /home/pi/minecraft/BuildTools.jar
    - name: Build Jar file
      shell: /usr/bin/java -jar /home/pi/minecraft/BuildTools.jar
    - name: Get spigot file name
      shell: /bin/ls /home/pi/minecraft | grep spigot*.jar
      register: ls_output
    - name: Edit Minecraft script
      lineinfile:
        path: /home/pi/minecraft/minecraft.sh
        regexp: 'screen'
        line: 'screen -S minecraft -d -m java -jar  -Xms512M -Xmx1008M {{ ls_output.stdout }} nogui  && break'
    - name: Start Minecraft Server
      shell: /home/pi/minecraft/minecraft.sh
...