---
- hosts: Minepi_Group
  name: Update Minecraft Server
  gather_facts: False
  tasks:
    - name: Edit rc.local
      lineinfile:
        path: "/etc/rc.local"
        regexp: '^su -l pi'
        line: 'su -l pi -c {{ mc_path }}/minecraft.sh'
      become: yes
