---
- hosts: Test_Group
  name: Get Palo Disk usage
  gather_facts: False
  roles:
    - pan
  tasks:
    - name: Get disk usage from Palo API
      uri:
        url: "{{ pan.api.url }}?type=config&action=get&xpath=/config/mgt-config/users&key={{ pan.api.key }}"
        validate_certs: no
        return_content: yes
      register: data
    - name: Convert the XML response data to JSON
      set_fact:
        api: "{{ data.content|xml2json}}"
    - debug: msg="{{ api.response.result.users }}"
    - name: Print admin users and roles
      debug: msg="User {{ item.@name }} has the {{ item.permissions.role-based.keys() }} role."
      with_dict:
        - "{{ api | from_json }}"