---
- hosts: Test_Group
  name: Get Palo Disk usage
  gather_facts: False
  roles:
    - pan
  tasks:
    - name: Get disk usage from Palo API
      uri:
        url: "{{ pan.api.url }}?type=config&action=get&xpath=/config/mgt-config/users&key={{ pan.api.key }}"
        validate_certs: no
        return_content: yes
      register: data
    - debug: msg="{{ lookup('xmlfile', data.content)|xml2json }}"