---
- hosts: Minepi_Group
  name: Update Minecraft Server
  gather_facts: False
  roles:
    - pan
  tasks:
    - name: Get disk usage from Palo API
      uri: "{{ pan.api.url }}?type=get&action=get&xpath=/config/mgt-config/users&key={{ pan.api.key }}"
      return_content: yes
    register: data
    - name: print return data
      msg: These are the firewall admin users
      var: data.content